package com.niluverse.uninex.notification;

import java.time.Instant;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * A real event notification for one recipient -- generated by the actual
 * booking/incident lifecycle (see BookingService/IncidentService), not a
 * standalone demo feature. Persisted so there is a real notification
 * history/inbox, in addition to the live SSE push while connected.
 */
@Document(collection = "notifications")
public class Notification {

    @Id
    private String id;

    private String recipientEmail;
    private NotificationType type;
    private String message;
    private String relatedResourceId;
    private boolean read = false;
    private Instant createdAt = Instant.now();

    public Notification() {
    }

    public Notification(String recipientEmail, NotificationType type, String message, String relatedResourceId) {
        this.recipientEmail = recipientEmail;
        this.type = type;
        this.message = message;
        this.relatedResourceId = relatedResourceId;
        this.read = false;
        this.createdAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRecipientEmail() {
        return recipientEmail;
    }

    public void setRecipientEmail(String recipientEmail) {
        this.recipientEmail = recipientEmail;
    }

    public NotificationType getType() {
        return type;
    }

    public void setType(NotificationType type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getRelatedResourceId() {
        return relatedResourceId;
    }

    public void setRelatedResourceId(String relatedResourceId) {
        this.relatedResourceId = relatedResourceId;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
